### ISSUE TITLE
TODO for 1.0.0

### ISSUE THREAD

**Issue by PhilipShilling** [PhilipShilling/TwitchBot#2]
- [x] Block links by default
- [x] Add logging for developers
- [x] Simple control panel
- [ ] Implement modules
- [ ] Create all default items
- [ ] Create an installer for clean workspace
